
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 20
y = 20

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[general]
live_config_reload = true
import = [
	"~/.config/alacritty/themes/iterm.toml"
]

